In [17]:
import pandas as pd
import numpy as np


In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [18]:
df=pd.read_csv("/content/drive/MyDrive/DM & ML LAB/Dataset/iris.csv")

In [19]:
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.4           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.3          0.2     setosa
4             5.1          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [23]:
print(df.head(10))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.4           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.3          0.2  setosa
4           5.1          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa


In [24]:
print(df.tail(10))

     sepal_length  sepal_width  petal_length  petal_width    species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica


In [27]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [29]:
df.dtypes


sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

loc
1.label based
2.loc boolean
3.multiple colum

iloc
1.index based
2.numerical
3.single based

In [30]:
df.loc[0:4]

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.4           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.3          0.2  setosa
4           5.1          3.6           1.4          0.2  setosa

In [31]:
df.loc[0:4,['sepal_width']]

sepal_width
0          3.5
1          3.4
2          3.2
3          3.1
4          3.6

In [32]:
df.loc[0:4,['sepal_width','petal_width']]

sepal_width  petal_width
0          3.5          0.2
1          3.4          0.2
2          3.2          0.2
3          3.1          0.2
4          3.6          0.2

In [34]:
df.iloc[0:4,0:3]

sepal_length  sepal_width  petal_length
0           5.1          3.5           1.4
1           4.9          3.4           1.4
2           4.7          3.2           1.3
3           4.6          3.1           1.3

In [35]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [36]:
max(df['sepal_length'])

7.9

In [37]:
min(df['sepal_length'])

4.3

In [41]:
np.average(df['sepal_length'])

5.843999999999999

find out the unique values for sepal width only for before 7th index

In [44]:
pd.unique(df['sepal_width'][0:7])

array([3.5, 3.4, 3.2, 3.1, 3.6, 3.9])

In [45]:
pd.unique(df.loc[0:6, 'sepal_width'])

array([3.5, 3.4, 3.2, 3.1, 3.6, 3.9])

In [46]:
pd.unique(df.iloc[0:7, 1])

array([3.5, 3.4, 3.2, 3.1, 3.6, 3.9])

In [60]:
pd.unique(df.loc[0:6, ['sepal_width', 'petal_width', 'sepal_length','petal_length']].values.ravel())



array([3.5, 0.2, 5.1, 1.4, 3.4, 4.9, 3.2, 4.7, 1.3, 3.1, 4.6, 3.6, 3.9,
       0.4, 5.4, 1.7, 0.3])